### ISSUE TITLE
Readme for Installation

### ISSUE THREAD

**Issue by JaciBrunning** [TrinityTrihawks/2016#13]
Don't mind me, just browsing people's Toast repos :V

Hotplate and Ruby installation is only needed for if you're creating a module from scratch. For people cloning the repo, all they need to do is run `gradlew idea` or `gradlew eclipse`. The Team Number can be changed within the build.gradle file.

Steps:  
1) Clone the repo
2) Run `gradlew eclipse` or `gradlew idea` for your respective IDE (linux/mac users should prefix `gradlew` with `./`)
3) Edit the `build.gradle` file to reflect the configuration you desire (e.g. changing the team number if applicable)  

Happy Coding :+1:

**Comment by RuijieYu** [comment]
Thank you so much for explaining this..

**Comment by WawerOS** [comment]
Closed with commit  de134e65
